### ISSUE TITLE
SignUp by phone number

### ISSUE THREAD

**Issue by RodionBezruk** [cubiclesoft/sso-server#14]
Hi, 

I like your project and interesting start to use. Is it possible to add possibility configure SignUp functionality such as: 
- User can SignUp by Phone number ( without email ) , with confirm of phone number owner ( validate code ). 
or as alternative
- User can SignUp by Email ( what you have currently )

And SignIn also want to be more flexible: 
- Use can SignIn via Email ( existing )
- Use can SignIn via Username ( existing )
- Use can SignIn via Phone number ( not yet  )

Waiting on your response, Thank you!

**Comment by cubiclesoft** [comment]
This is an interesting feature request.  I don't think signing up solely by phone number makes a lot of sense as people change phone numbers quite frequently without access to the previous number.  However, having it as a sign in option could be useful for some websites.

Phone numbers are more complex to type in than a user might expect.  If a user types in `123-4567`, is that a valid phone number?  To the user it probably is.  Requiring the user to type in their full number, including country code `1-123-123-1234` could be a minor nuisance.

**Comment by RodionBezruk** [comment]
To make much more easily for users enter / fill their phone number, I suggest to use library with Autocomplete + Autodetect + Validation per country, such as: https://intl-tel-input.com/ 
Example with Country detect can be found by this link: 
https://intl-tel-input.com/node_modules/intl-tel-input/examples/gen/default-country-ip.html

Phone number for a lot of countries is start to using such as national User ID , Mobile ID , Passport ID and etc. So phone number for a lot of people is using such as identity / passport of the person.   

Let me know if possible from your side to make this feature implementation for LogIn / SignUp / Reset password by phone number ? As I see, sms provider to verify phone number and for reset password already implemented to your system ( btw , very interesting solution ) ;)

**Comment by cubiclesoft** [comment]
Thanks for the library tip.  There are no plans to implement this during this year.  But this is about the time of year when I start planning next year's official roadmap.  I'll keep it in mind as I plan out the next year's worth of dev tasks.  That's the best I can offer.

> As I see, sms provider to verify phone number and for reset password already implemented to your system ( btw , very interesting solution ) ;)

Uh...thanks.  It's the best, no-cost solution I could come up with at the time I implemented it.  However, you should know that it is also a bit buggy - if you send too many messages via those SMS gateways in a short period of time, it can trigger temporary blacklisting.  I recently came across a far better solution.

**Comment by cubiclesoft** [comment]
I'm not going to implement a phone number only login feature.  A user could enter their phone number for their username if they want to go that route but that's up to the user.  A lot of people in the U.S. rotate phone numbers, so phone number login would be a hassle, not a feature.  Plus, there are privacy and security implications of storing PII information that might violate GDPR + make user accounts easily guessed.  You could probably hijack the username field for phone number by using a language mapping file to dynamically replace strings and use a custom module to inject Javascript/CSS to transform the field.  The user wouldn't notice the difference but I'm not going to support such a feature due to the risks.

There is now a new 2FA module for Generic Login that implements reverse SMS using a Twilio-compatible service.  It's not a free solution but SignalWire makes reverse SMS 2FA reasonably affordable for U.S./Canada-based websites (maybe around $1/month RECEIVING messages vs. spending hundreds to thousands of dollars/month SENDING messages).  The module does not implement SMS account recovery partly because I was lazy and partly because SMS isn't a secure medium from source spoofing.

I'm not keen on dropping in an additional ~300KB for a JS library + images just for client-side phone number validation at this time.

The decisions above + the new 2FA module closes out this issue.
