### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by maksym-prikhodko** [cubiclesoft/sso-server#17]
When I register my own user and verify - I can't to login. I get the message "Your account has insufficient permissions to access that resource." but cookies are dropped

**Comment by cubiclesoft** [comment]
I see you closed this issue.  But since Google indexes issues, I'll reply.  This is probably caused by following the example setup, which includes code for a permissions check.  Since the user account you signed in with doesn't have the specific permission, it gets kicked back out with that error message.  The login succeeded but then the application rejects the user.  Two options:  Add the permission to the user account via the admin OR comment out that line of code in the client application (i.e. remove the permission check).
