### ISSUE TITLE
Update database field

### ISSUE THREAD

**Issue by FlurryNight** [cubiclesoft/sso-server#21]

**Comment by cubiclesoft** [comment]
You need to make sure the API key has read/write on the mapped field.  Pass 'true' when you call:

```php
$sso_client->LoadUserInfo(true);
```

It's not exactly intuitive.  When you pass 'true', what happens is the call attempts to push locally updated values into the SSO server and then updates local information so it is in sync with the SSO server.

Note that this will only work for certain providers (e.g. Generic Login).  Most of the other providers (e.g. social media) disallow overwriting regardless of the API key setup (i.e. provider rules take precedence) because the provider will overwrite the values the next time the person logs in.

**Comment by ZR3SYSTEMS** [comment]
Thank you very much, I confess that I did not pay attention to this function,

Im making a basic profile dashboard ( later a web app :) )

User info ->
email,- working
firstname,- working
lastname,- working
cdn url of uploaded image,- working now

statistics
AccountCreated - working

In admin dashboard there ´s a field called (last activated )wich is last login info

How can i get that too?

I have mapped the created date

also there´s one called (first_activated) is it that?

Thanks again.
keep developing such good things

Ps:When I finish developing the profile page I leave a photo here ok? for you to see

**Comment by cubiclesoft** [comment]
If it's not a formal SSO field or tag, it's possibly not able to be mapped?  It's been a while since I looked at the field mapping logic.

Any photo you post on the GitHub issue tracker is public.  So be sure to scrub sensitive information.

**Comment by FlurryNight** [comment]
Ok,thanks for all helpful information ,

Yes i know 😆
