### ISSUE TITLE
Verification/recovery via emails incorporating a hyperlink

### ISSUE THREAD

**Issue by sjbartley** [cubiclesoft/sso-server#25]
Corporate filtering is preventing many users from seeing their verification/recovery emails. Unfortunately, this is just the way it is - and it's getting worse - companies just can't risk another phishing/crypto attack. Even as our outgoing mail server complies with security/trustworthiness features, these emails are still getting blocked.

I think an option needs to be enabled for email verification/recovery via a simple 6-8 digit code sent via email, then entered/pasted by the user into a form.

Please let me know what you think, if I'm missing something already integrated, and/or how I can help.

Thank you.

**Comment by cubiclesoft** [comment]
An interesting idea.  Support for it would require a whole new verification screen after account creation.  Right now, the user is redirected back to the sign in screen and told to verify their account first before signing in.

Another related idea might be to display information to the user to get them to add the inevitable "From" address to their contacts list with their email provider before they click the Sign Up button.  That way their email server gives a boost to those messages and the messages are therefore more likely to deliver vs. hard bounce.

I think the first step though is to test to see if the 6-8 digit code idea will even work better in the first place.  The simplest solution is to temporarily alter the Recovery email by replacing the URL token with a test code (e.g. 123456) and then having a specific user who is encountering issues test the recovery email to see if that arrives or if it still gets blocked.  If it is still blocked, then it is something other than the URL tripping up the filters.  Not too many people are going to need to recover their account in a given day, so some temporary downtime might be fine.

About two weeks ago, I went through the whole song and dance to set up DKIM on my mail server.  I only had SPF prior to that, which worked fine for many years up until a few months ago.  It was challenging to get everything configured correctly due to a bunch of misinformation floating around on the Internet.  It took several days of configuration tweaks to get outbound mail messages to go from 4.1/10 to a 10/10 on `mail-tester.com`.

I just ran a test using the existing hyperlink method with `mail-tester.com` and got a 9.9 from the SSO server running on barebonescms.com.  The DKIM check in the SpamAssassin section failed but was a false positive, so the actual score should have been 10/10.  According to that site, I see nothing wrong.

I also just ran a test using the existing hyperlink method  on `isnotspam.com` and got all passes across the board, including a declaration of "ham."  Also, the SpamAssassin DKIM check passed.  However, the spam score was 3.7 and the message hit both the BAYES_99 and BAYES_999 rules.  Their threshold for spam is 10.  Since 3.7 < 10, the message was declared as ham.  3.7 isn't ideal but it's not anywhere near the average spam threshold.  Verification emails are a fairly normal thing and do have some spam-like characteristics to them that might trigger those two rules (verify your e-mail, click this link, here's some information you entered, etc).

In both cases, SpamAssassin didn't consider a verification hyperlink in the message to be an issue but _did_ apply a negligible score to the HTML that was in the messages.

By all rights, the SSO server is operating normally in production.  Any given email system will classify any given message as spam and/or block bounce.  It's impossible to accommodate all of them.  Some server operators like Hotmail/Live/Outlook.com require email server owners (i.e. people like you and me who run private servers) to ask to be added to their whitelist to send email to their users and they periodically clear the whitelist.  My general recommendation is to mostly ignore broken email servers that violate IETF Standards.  Life is better without worrying about them.

**Comment by sjbartley** [comment]
Thank you for the detailed response - which shows you've thought through the issues (and my assumptions).

Sending an account verification link from our server to mail-tester.com gets a 9.9 - with the usual false-positive on DKIM (reverse DNS lookup), etc...

This issue is affecting a reasonable proportion of important users, and I can't work out how to make the verification process reliable.

**Comment by cubiclesoft** [comment]
Can you try removing the link part of the email and just sending a test code in its place?  Obviously that won't do anything but let's make sure that it actually has better metrics before investing time building something that might not work any better.

**Comment by sjbartley** [comment]
OK - I'll reply when I have some test results. Thanks.

**Comment by sjbartley** [comment]
Sorry, you may just want to close this issue for now. Often these recovery/verification issues relate to user incompetence; and once the user has been helped, they aren't willing/able to help me get to the bottom of the problem.

**Comment by cubiclesoft** [comment]
Okay.  Closing.
