### ISSUE TITLE
Order of classes defined in /support/Net/DNS2.php (PHP 8.0)

### ISSUE THREAD

**Issue by sjbartley** [cubiclesoft/sso-server#26]
I had to re-order the classes in  /support/Net/DNS2.php for PHP 8. It seems that a class must now be declared before it can be inherited/extended.

You can see my revision at https://github.com/unicarehealth/sso-server/blob/master/support/Net/DNS2.php

**Comment by cubiclesoft** [comment]
I don't update PHP to the next major release until the 4th point release (e.g. 7.4.4, 8.0.4).  That allows all of the major bugs to settle, especially CVE's.  The healthcare industry should generally be a tad more tentative about upgrading core software like PHP since it manages sensitive data.

I've found over the years that waiting for the 4th point release (approximately 4-6 months) allows for PHP to stabilize to a point that I'm comfortable with.  For example, PHP 8 added a JIT, which probably has lots of problems lurking in it.  Ubuntu 20.04 LTS only rolled out 7.4 via apt, so it's at least 3 years out before Ubuntu LTS sees PHP 8 and therefore at least 5 years before PHP 8 is seen globally on the majority of systems.  Not that I'll wait that long to fix this, but rushing to immediately upgrade PHP is generally not a great idea.  I always look at the PHP changelog to see when things have settled into a normal pattern.

[Net::DNS2](https://github.com/mikepultz/netdns2) is a third-party library that runs through a custom PHP minifier to reduce its overall size (not [Decomposer](https://github.com/cubiclesoft/php-decomposer)).  The library is part of [Ultimate Email Toolkit](https://github.com/cubiclesoft/ultimate-email), which probably shares a similar problem in PHP 8.0.  Fixing this will probably be done upstream in Ultimate Email Toolkit and then deployed across all projects using [File Tracker](https://file-tracker.cubiclesoft.com/).

**Comment by sjbartley** [comment]
Thanks for the response and explanation of where this issue comes from, etc... I'm sure the rest of your advice comes from years of experience. I've been testing our systems for PHP8 compliance, and this was one issue that cropped up.

JIT compilation doesn't seem to be relevant to many people at the moment; I don't think the exemplary PHP.ini files (included with PHP8) even include the keys required to turn it on! We'll see whether that becomes worth using on web applications in time.

A point against waiting until x.04 in the case of PHP is that strict typing improvements and thus better static analysis allow for better quality code, quicker/safer enhancements, etc... Most other platforms I work on have typing as a core feature, so there is no gain this way.

**Comment by cubiclesoft** [comment]
Upstream projects fixed.  This and a few other issues are fixed.  PHP 8.1 now confirmed working.
