### ISSUE TITLE
Importing credentials from client application

### ISSUE THREAD

**Issue by anywheresa** [cubiclesoft/sso-server#31]
Hi
First of all, great product!

I am trying to import users from an existing application. I have two issues and a question as well.

1. I get an error with my field mapping....
$mapinfo = array(first_name  => $row["sFirst_Name"],
    last_name => $row["sLast_Name"],);
PHP Warning:  Use of undefined constant first_name - assumed 'first_name' (this will throw an Error in a future version of PHP) 

Then, I do not pick up the Blowfish class.
I added a reference to it but still get an error.

PHP Fatal error:  Uncaught Error: Class 'Blowfish' not found in.....

Then my question...
I am bringing the password from the client app in as is. In other words it is encrypted with whatever encryption method the developer used. Is that fine as I see further encryption is being applied. Or must I bring the password in as cleartext?
Thank you
Deon

**Comment by cubiclesoft** [comment]
Encryption is not the same thing as hashing.  Hashes are one-way functions.  Weak passwords can be guessed by brute forcing billions of hashes or using common password lists but otherwise can't be determined.  Encryption, on the other hand, is reversible to the cleartext.

You could set up your existing users in such a way that it requires them to recover their account and, in the process, set their password.

Blowfish is not used for encryption but rather for its expensive key schedule for BCrypt-style hashing.  Newer versions of the software use the built-in PHP mechanism for generating password hashes.  So if your existing software uses built-in PHP password hashing functions (e.g. the [password_hash](https://www.php.net/manual/en/function.password-hash) function), your existing passwords MAY be compatible as-is - you'll have to look at the source code of both products.

As to the warning emitted by PHP, you need to wrap keys in quotes.  `"first_name"` instead of `first_name`.  The former is a string.  The latter is an attempt to reference a non-existent constant, hence the warning from PHP.

This is more of a support request than an actual issue with the software, so I'm going to close this.
