### ISSUE TITLE
Admin Panel Not Working

### ISSUE THREAD

**Issue by felischmi2003** [cubiclesoft/sso-server#35]
Hello,
I had this issue a second time.... Please Help: 

> I have the Script uploading above the Server.
> I installed this Step by Step.
> Than works the Admin Panel.
> After a short time, when i reload the site,than whiteb screen.
> are the API is Working. This Problem had I the last 24 h ever!
> After ever new Installation!
> 
> I hosted the Script above a Plesk Windows Server, and have all permissions.
> 
> Please help me everyone!
> With best regrades,
> Felix Schmitt
> 
> (P.s. Sorry for my englisch, i come from germany)
>

**Comment by cubiclesoft** [comment]
It's probably because your public IP address changed in the interim.  The default `admin_hook.php` limits access to the admin interface to the IP address of the person installing the software.

Figure out what your new public IP is, update `admin_hook.php`, and continue.  The installation documentation eventually walks through the process of setting up a SSO client and replacing `admin_hook.php` so it uses the SSO server/client to login to the admin interface.

**Comment by felischmi2003** [comment]
Thanks a lot
