### ISSUE TITLE
Miscellaneous fixes

### ISSUE THREAD

**Issue by sjbartley** [cubiclesoft/sso-server#37]
A few quick fixes.

1) index.php line 150:
'non-offical' should be 'non-official'.

2) sso_remember_me.php starting at line 310:
Replace $this->activemodules with $activemodules as it is just a local variable.

3) index.php line 185 - add field $activemodules:
protected array $activemodules = [];

Incorporating PhpDoc would mean adding two lines:

/** @var array<string, string> */
protected array $activemodules = [];

Will you accept pull requests for these sorts of changes?

**Comment by sjbartley** [comment]
A few more in phpqrcode.php I know some files in the application are downstream/pulled from other projects, but these may be straightforward:

1) eatKanji() has 'return $run;' that should be 'return $ret;'.

2) getCode() has a line that's just '$ret;' which should be removed.

3) estimateBitsModeKanji() should be a static function like those around it (it is only ever called statically).

4) encodeModeKanji() has typo 'QRbitrtream()' which should be the obvious 'QRbitstream()'.

5) class QRtools should have first line 'public static array $frames = [];' to declare the static property used later.

6) class qrstr should be renamed QRstr (as it is called later).

**Comment by cubiclesoft** [comment]
Fixed the spelling mistake.  The rest are irrelevant.  I hand-write my documentation.  I don't want/need a tool to do that for me.

phpqrcode.php is a third-party library.  Fixing it must be done upstream so that everyone benefits instead of fragmenting code bases.  Also, your first proposed fix is actually wrong.  If you look at the surrounding functions, `$run = $p` is the official assignment.  Since neither you nor I have any idea what that function is supposed to do, leaving it as-is is the only option unless you want to become an expert in QR codes (trust me, that's a bad idea).  Also, the default "hint mode," whatever that is, appears to be `QR_MODE_8`, which means that the code bits related to Kanji will never execute anyway.  It does look like that library isn't being maintained as the last update was a decade ago but there isn't any particularly good replacement class available - unless I want to use a "modern" PHP class by someone who immaturely just puts emoji characters as their commit messages, which I don't.  Most of your issues with that class are also irrelevant (e.g. PHP is case-insensitive, so qrstr and QRstr are functionally identical).  At any rate, QR codes are only generated when using 2FA and, since the class works for that limited use-case, there's nothing to do here.

Closing.

**Comment by sjbartley** [comment]
Thanks for checking the issues over. Sorry, eatKanji() probably is missing line '$run = $p' as per the other functions. 

I'm not proposing PhpDoc for documentation at all - just the clarity it brings to parameters, return values and variables, and the way correctness can the be checked with tools.
