### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by shepherdscribe** [cubiclesoft/sso-server#39]
Hi I followed the youtube video and I got the following error even though my local setup is correct.
OS: OSX using Valet

<img width="481" alt="Screen Shot 2022-11-28 at 4 19 00 PM" src="https://user-images.githubusercontent.com/62448059/204228096-2a9f0984-4951-4d1c-b2fb-1e9e45c5412c.png">

<img width="722" alt="Screen Shot 2022-11-28 at 4 18 18 PM" src="https://user-images.githubusercontent.com/62448059/204227663-9d75e747-6f56-4b68-9077-b1bad226a66e.png">

**Comment by cubiclesoft** [comment]
So I'm guessing you are doing something unusual to enable SSL/TLS on a fake domain.  `cubesoft.test` is probably DNS and TLS hijacked in some way on your local machine?  The SSO server/client software uses public SSL/TLS certs in the `support/cacerts.pem` file rather than system/OS certs.  In other words, the SSO client won't use your custom TLS server certificate unless you either put it into or replace cacerts.pem or point the SSO client at the correct certificate on the system.

**Comment by shepherdscribe** [comment]
Thanks. I'll try it on my production server.
